spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2;mode=PostgreSQL
    username: sa
    password: sa
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
